name: Upgrade Dependencies

on:
  schedule:
    - cron:  '0 10 * * 1'
  push:
    branches: [main]

jobs:
  upgrade-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: init hermit
        run: ./bin/hermit env --raw >> $GITHUB_ENV

      - name: Check write access to repo
        run: |
          token_login=$(curl -H "Authorization: Bearer ${token}" https://api.github.com/user | jq -r '.login')
          echo token login is ${token_login}
          echo $(curl  -H "Authorization: Bearer ${token}" https://api.github.com/repos/${repo}/collaborators/${token_login}/permission) > result
          cat result | jq  '.permission == "admin" // .permission == "write"' > /dev/null || ( echo "Token does not have write access to ${repo}" >> ${GITHUB_STEP_SUMMARY}; exit 1)
          curl -sS -f -I -H "Authorization: Bearer ${token}" https://api.github.com | grep 'x-oauth-scopes:' | grep 'repo' > /dev/null && exit 0 || echo "Token does not have repo scope on ${repo}" >> ${GITHUB_STEP_SUMMARY}
        env:
          repo: ${{ github.repository }}
          token: ${{ secrets.UPGRADE_GITHUB_TOKEN }}

      - name: upgrade hermit dependencies
        run: hermit upgrade

      - name: upgrade go dependencies
        run: go get -t -u ./...

      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: Upgrade dependencies
            title: Upgrade dependencies
            body: |
              - Upgrade hermit and go dependencies
  
              Auto-generated by a Github Action
            branch: upgrade-dependencies
            token: ${{ secrets.UPGRADE_GITHUB_TOKEN }} 
